name: CloudAC
version: '${project.version}'
main: mrresi.cloudac.CloudAC
api-version: '1.16'
author: MrResi, SkyDev
depend: [packetevents]

commands:
  cloudac:

permissions:
  cloudac.admin:
    default: op
  cloudac.alerts:
    default: op
  cloudac.bypass:
    default: op
